arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - link1_joint
    - link2_joint
    - link3_joint
  gains:
    link1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper_joint1
    - gripper_joint2
  gains:
    gripper_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1